set(src_list
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_cbc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_cfb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_ige.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_misc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_ofb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/aes_wrap.c
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/gen/linux_arm/aes-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/gen/linux_arm/aesv8-armx.S
    ${PROJECT_SOURCE_DIR}/src/crypto/aes/gen/linux_arm/bsaes-armv7.S
    ${PROJECT_SOURCE_DIR}/src/crypto/aria/aria.c
    ${PROJECT_SOURCE_DIR}/src/crypto/armcap.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_bitstr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_d2i_fp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_digest.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_dup.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_gentm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_i2d_fp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_int.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_mbstr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_object.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_octet.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_strex.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_strnid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_time.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_type.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_utctm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_utf8.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/a_verify.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/ameth_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn1_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn1_gen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn1_item_list.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn1_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn1_parse.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn_mime.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn_moid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn_mstbl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/asn_pack.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/bio_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/bio_ndef.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/d2i_param.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/d2i_pr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/d2i_pu.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/evp_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/f_int.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/f_string.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/i2d_evp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/n_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/nsseq.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/p5_pbe.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/p5_pbev2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/p5_scrypt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/p8_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/t_bitst.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/t_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/t_spki.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_dec.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_fre.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_new.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_scn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_typ.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/tasn_utl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_algor.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_bignum.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_info.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_int64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_long.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_sig.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_spki.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1/x_val.c
    ${PROJECT_SOURCE_DIR}/src/crypto/asn1_dsa.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/arch/async_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/arch/async_posix.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/arch/async_win.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/async.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/async_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/async/async_wait.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bf/bf_cfb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bf/bf_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bf/bf_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bf/bf_ofb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bf/bf_skey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_buff.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_lbuf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_nbio.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_prefix.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bf_readbuff.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_addr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_cb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_dump.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_sock.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bio_sock2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_acpt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_bio.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_conn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_core.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_dgram.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_dgram_pair.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_fd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_file.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_log.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_mem.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/bss_sock.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bio/ossl_core_bio.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_add.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_asm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_blind.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_const.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_conv.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_ctx.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_depr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_dh.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_div.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_exp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_exp2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_gcd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_gf2m.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_intern.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_kron.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_mod.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_mont.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_mpi.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_mul.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_nist.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_prime.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_rand.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_recp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_rsa_fips186_4.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_shift.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_sqr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_sqrt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_srp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_word.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/bn_x931p.c
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/gen/linux_arm/armv4-gf2m.S
    ${PROJECT_SOURCE_DIR}/src/crypto/bn/gen/linux_arm/armv4-mont.S
    ${PROJECT_SOURCE_DIR}/src/crypto/bsearch.c
    ${PROJECT_SOURCE_DIR}/src/crypto/buffer/buf_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/buffer/buffer.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/camellia.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_cbc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_cfb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_ctr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_misc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/camellia/cmll_ofb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cast/c_cfb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cast/c_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cast/c_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cast/c_ofb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cast/c_skey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/chacha/gen/linux_arm/chacha-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/cmac/cmac.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_asn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_client.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_ctx.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_genm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_hdr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_http.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_msg.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_protect.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_server.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_status.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_util.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cmp/cmp_vfy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_att.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_cd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_dd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_dh.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_ec.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_env.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_ess.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_io.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_kari.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_pwri.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_rsa.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_sd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cms/cms_smime.c
    ${PROJECT_SOURCE_DIR}/src/crypto/comp/c_brotli.c
    ${PROJECT_SOURCE_DIR}/src/crypto/comp/c_zlib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/comp/c_zstd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/comp/comp_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/comp/comp_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_api.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_def.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_mall.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_mod.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_sap.c
    ${PROJECT_SOURCE_DIR}/src/crypto/conf/conf_ssl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/context.c
    ${PROJECT_SOURCE_DIR}/src/crypto/core_algorithm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/core_fetch.c
    ${PROJECT_SOURCE_DIR}/src/crypto/core_namemap.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cpt_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cpuid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/crmf/crmf_asn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/crmf/crmf_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/crmf/crmf_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/crmf/crmf_pbm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cryptlib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_b64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_log.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_oct.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_policy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_sct.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_sct_ctx.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_vfy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ct/ct_x509v3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ctype.c
    ${PROJECT_SOURCE_DIR}/src/crypto/cversion.c
    ${PROJECT_SOURCE_DIR}/src/crypto/der_writer.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/cbc_cksm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/cbc_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/cfb64ede.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/cfb64enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/cfb_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/des_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/ecb3_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/ecb_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/fcrypt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/fcrypt_b.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/ofb64ede.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/ofb64enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/ofb_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/pcbc_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/qud_cksm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/rand_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/set_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/str2key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/des/xcbc_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/deterministic_nonce.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_ameth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_check.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_depr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_gen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_group_params.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_kdf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_pmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dh/dh_rfc5114.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_ameth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_check.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_depr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_gen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_ossl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_pmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dsa/dsa_vrf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_dl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_dlfcn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_openssl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_vms.c
    ${PROJECT_SOURCE_DIR}/src/crypto/dso/dso_win32.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ebcdic.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve25519.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/arch_32/f_impl32.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/arch_64/f_impl64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/curve448.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/curve448_tables.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/eddsa.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/f_generic.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/curve448/scalar.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec2_oct.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec2_smpl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_ameth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_check.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_curve.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_cvt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_deprecated.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_kmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_mult.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_oct.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_pmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ec_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecdh_kdf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecdh_ossl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecdsa_ossl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecdsa_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecdsa_vrf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/eck_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecp_mont.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecp_nist.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecp_nistz256.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecp_oct.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecp_smpl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecx_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecx_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/ecx_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ec/gen/linux_arm/ecp_nistz256-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/decoder_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/decoder_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/decoder_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/decoder_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/encoder_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/encoder_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/encoder_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/encode_decode/encoder_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_all.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_cnf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_ctrl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_dyn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_fat.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_init.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_list.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_openssl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_rdrand.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/eng_table.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_asnmth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_cipher.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_dh.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_digest.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_dsa.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_eckey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_pkmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_rand.c
    ${PROJECT_SOURCE_DIR}/src/crypto/engine/tb_rsa.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_all.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_all_legacy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_blocks.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_mark.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/err/err_save.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ess/ess_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ess/ess_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ess/ess_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/asymcipher.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/bio_b64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/bio_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/bio_md.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/bio_ok.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/c_allc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/c_alld.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/cmeth_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/ctrl_params_translate.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/dh_ctrl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/dh_support.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/digest.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/dsa_ctrl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_aes.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_aes_cbc_hmac_sha1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_aes_cbc_hmac_sha256.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_aria.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_bf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_camellia.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_cast.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_chacha20_poly1305.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_des.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_des3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_idea.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_old.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_rc2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_rc4.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_rc4_hmac_md5.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_rc5.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_seed.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_sm4.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/e_xcbc_d.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/ec_ctrl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/ec_support.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/encode.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_cnf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_fetch.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_pbe.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_rand.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/evp_utils.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/exchange.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/kdf_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/kdf_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/kem.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/keymgmt_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/keymgmt_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/legacy_blake2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/legacy_md5.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/legacy_md5_sha1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/legacy_ripemd.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/legacy_sha.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/m_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/m_sigver.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/mac_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/mac_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/names.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p5_crpt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p5_crpt2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_dec.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_legacy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_open.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_seal.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/p_verify.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/pbe_scrypt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/pmeth_check.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/pmeth_gn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/pmeth_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/evp/signature.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ex_data.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_dh.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_key_generate.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_key_validate.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_params.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_params_generate.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ffc/ffc_params_validate.c
    ${PROJECT_SOURCE_DIR}/src/crypto/gen/linux_arm/armv4cpuid.S
    ${PROJECT_SOURCE_DIR}/src/crypto/gen/linux_arm/params_idx.c
    ${PROJECT_SOURCE_DIR}/src/crypto/getenv.c
    ${PROJECT_SOURCE_DIR}/src/crypto/hmac/hmac.c
    ${PROJECT_SOURCE_DIR}/src/crypto/hpke/hpke.c
    ${PROJECT_SOURCE_DIR}/src/crypto/hpke/hpke_util.c
    ${PROJECT_SOURCE_DIR}/src/crypto/http/http_client.c
    ${PROJECT_SOURCE_DIR}/src/crypto/http/http_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/http/http_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/idea/i_cbc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/idea/i_cfb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/idea/i_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/idea/i_ofb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/idea/i_skey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/info.c
    ${PROJECT_SOURCE_DIR}/src/crypto/init.c
    ${PROJECT_SOURCE_DIR}/src/crypto/initthread.c
    ${PROJECT_SOURCE_DIR}/src/crypto/kdf/kdf_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/lhash/lh_stats.c
    ${PROJECT_SOURCE_DIR}/src/crypto/lhash/lhash.c
    ${PROJECT_SOURCE_DIR}/src/crypto/md5/md5_dgst.c
    ${PROJECT_SOURCE_DIR}/src/crypto/md5/md5_one.c
    ${PROJECT_SOURCE_DIR}/src/crypto/md5/md5_sha1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/mem.c
    ${PROJECT_SOURCE_DIR}/src/crypto/mem_sec.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/cbc128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/ccm128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/cfb128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/ctr128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/cts128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/gcm128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/gen/linux_arm/ghash-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/gen/linux_arm/ghashv8-armx.S
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/ocb128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/ofb128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/siv128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/wrap128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/xts128.c
    ${PROJECT_SOURCE_DIR}/src/crypto/modes/xts128gb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/o_dir.c
    ${PROJECT_SOURCE_DIR}/src/crypto/o_fopen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/o_init.c
    ${PROJECT_SOURCE_DIR}/src/crypto/o_str.c
    ${PROJECT_SOURCE_DIR}/src/crypto/o_time.c
    ${PROJECT_SOURCE_DIR}/src/crypto/objects/o_names.c
    ${PROJECT_SOURCE_DIR}/src/crypto/objects/obj_dat.c
    ${PROJECT_SOURCE_DIR}/src/crypto/objects/obj_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/objects/obj_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/objects/obj_xref.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_asn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_cl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_ext.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_http.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_srv.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/ocsp_vfy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ocsp/v3_ocsp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/packet.c
    ${PROJECT_SOURCE_DIR}/src/crypto/param_build.c
    ${PROJECT_SOURCE_DIR}/src/crypto/param_build_set.c
    ${PROJECT_SOURCE_DIR}/src/crypto/params.c
    ${PROJECT_SOURCE_DIR}/src/crypto/params_dup.c
    ${PROJECT_SOURCE_DIR}/src/crypto/params_from_text.c
    ${PROJECT_SOURCE_DIR}/src/crypto/passphrase.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_all.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_info.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_oth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_pk8.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_pkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_x509.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pem_xaux.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pem/pvkfmt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_add.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_asn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_attr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_crpt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_crt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_decr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_init.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_kiss.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_mutl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_npas.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_p8d.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_p8e.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_sbag.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/p12_utl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs12/pk12err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/bio_pk7.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_attr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_doit.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_mime.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pk7_smime.c
    ${PROJECT_SOURCE_DIR}/src/crypto/pkcs7/pkcs7err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/poly1305/gen/linux_arm/poly1305-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/poly1305/poly1305.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/defn_cache.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/property.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/property_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/property_parse.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/property_query.c
    ${PROJECT_SOURCE_DIR}/src/crypto/property/property_string.c
    ${PROJECT_SOURCE_DIR}/src/crypto/provider.c
    ${PROJECT_SOURCE_DIR}/src/crypto/provider_child.c
    ${PROJECT_SOURCE_DIR}/src/crypto/provider_conf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/provider_core.c
    ${PROJECT_SOURCE_DIR}/src/crypto/provider_predefined.c
    ${PROJECT_SOURCE_DIR}/src/crypto/punycode.c
    ${PROJECT_SOURCE_DIR}/src/crypto/quic_vlint.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/prov_seed.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_deprecated.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_pool.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/rand_uniform.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rand/randfile.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc2/rc2_cbc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc2/rc2_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc2/rc2_skey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc2/rc2cfb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc2/rc2ofb64.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc4/rc4_enc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rc4/rc4_skey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ripemd/rmd_dgst.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ripemd/rmd_one.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_ameth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_backend.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_chk.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_crpt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_depr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_gen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_mp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_mp_names.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_none.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_oaep.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_ossl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_pk1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_pmeth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_pss.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_saos.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_schemes.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_sp800_56b_check.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_sp800_56b_gen.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_x931.c
    ${PROJECT_SOURCE_DIR}/src/crypto/rsa/rsa_x931g.c
    ${PROJECT_SOURCE_DIR}/src/crypto/seed/seed.c
    ${PROJECT_SOURCE_DIR}/src/crypto/seed/seed_cbc.c
    ${PROJECT_SOURCE_DIR}/src/crypto/seed/seed_cfb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/seed/seed_ecb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/seed/seed_ofb.c
    ${PROJECT_SOURCE_DIR}/src/crypto/self_test_core.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/gen/linux_arm/keccak1600-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/gen/linux_arm/sha1-armv4-large.S
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/gen/linux_arm/sha256-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/gen/linux_arm/sha512-armv4.S
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/sha1_one.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/sha1dgst.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/sha256.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/sha3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sha/sha512.c
    ${PROJECT_SOURCE_DIR}/src/crypto/siphash/siphash.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sleep.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm2/sm2_crypt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm2/sm2_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm2/sm2_key.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm2/sm2_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm3/legacy_sm3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm3/sm3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sm4/sm4.c
    ${PROJECT_SOURCE_DIR}/src/crypto/sparse_array.c
    ${PROJECT_SOURCE_DIR}/src/crypto/srp/srp_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/srp/srp_vfy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/stack/stack.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_init.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_register.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_result.c
    ${PROJECT_SOURCE_DIR}/src/crypto/store/store_strings.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/api.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/arch.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/arch/thread_none.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/arch/thread_posix.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/arch/thread_win.c
    ${PROJECT_SOURCE_DIR}/src/crypto/thread/internal.c
    ${PROJECT_SOURCE_DIR}/src/crypto/threads_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/threads_none.c
    ${PROJECT_SOURCE_DIR}/src/crypto/threads_pthread.c
    ${PROJECT_SOURCE_DIR}/src/crypto/threads_win.c
    ${PROJECT_SOURCE_DIR}/src/crypto/time.c
    ${PROJECT_SOURCE_DIR}/src/crypto/trace.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_asn1.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_conf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_req_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_req_utils.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_rsp_print.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_rsp_sign.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_rsp_utils.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_rsp_verify.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ts/ts_verify_ctx.c
    ${PROJECT_SOURCE_DIR}/src/crypto/txt_db/txt_db.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ui/ui_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ui/ui_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ui/ui_null.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ui/ui_openssl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/ui/ui_util.c
    ${PROJECT_SOURCE_DIR}/src/crypto/uid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/by_dir.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/by_file.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/by_store.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_cache.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_data.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_map.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_node.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/pcy_tree.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/t_crl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/t_req.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/t_x509.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_addr.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_admis.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_akeya.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_akid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_asid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_bcons.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_bitst.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_conf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_cpols.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_crld.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_enum.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_extku.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_genn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_group_ac.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_ia5.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_ind_iss.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_info.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_int.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_ist.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_lib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_ncons.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_no_ass.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_no_rev_avail.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_pci.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_pcia.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_pcons.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_pku.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_pmaps.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_prn.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_purp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_san.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_single_use.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_skid.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_soa_id.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_sxnet.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_tlsf.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_utf8.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3_utl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/v3err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_att.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_cmp.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_d2.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_def.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_err.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_ext.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_lu.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_meth.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_obj.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_r2x.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_req.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_set.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_trust.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_txt.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_v3.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_vfy.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509_vpm.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509cset.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509name.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509rset.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509spki.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x509type.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_all.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_attrib.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_crl.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_exten.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_name.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_pubkey.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_req.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_x509.c
    ${PROJECT_SOURCE_DIR}/src/crypto/x509/x_x509a.c
    ${PROJECT_SOURCE_DIR}/src/providers/baseprov.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/bio_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/capabilities.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_dsa_key.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_dsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_ec_key.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_ec_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_ecx_key.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_rsa_key.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_rsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_sm2_key.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/der_sm2_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_digests_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_dsa_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_ec_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_ecx_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_rsa_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_sm2_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/der/gen/linux_arm/der_wrap_gen.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/digest_to_nid.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/provider_ctx.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/provider_err.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/provider_seeding.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/provider_util.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/securitycheck.c
    ${PROJECT_SOURCE_DIR}/src/providers/common/securitycheck_default.c
    ${PROJECT_SOURCE_DIR}/src/providers/defltprov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/asymciphers/rsa_enc.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/asymciphers/sm2_enc.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha1_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_cbc_hmac_sha256_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_ccm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_ccm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_gcm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_gcm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_gcm_siv.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_gcm_siv_polyval.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_ocb.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_ocb_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_siv.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_siv_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_wrp.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_xts.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_xts_fips.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aes_xts_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria_ccm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria_ccm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria_gcm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria_gcm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_aria_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_blowfish.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_blowfish_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_camellia.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_camellia_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_cast5.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_cast5_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_chacha20.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_chacha20_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_chacha20_poly1305.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_chacha20_poly1305_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_cts.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_des.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_des_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_desx.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_desx_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_idea.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_idea_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_null.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc2.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc2_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc4.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc4_hmac_md5.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc4_hmac_md5_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_rc4_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_seed.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_seed_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_ccm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_ccm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_gcm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_gcm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_xts.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_sm4_xts_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_common.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_default.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_default_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_wrap.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/cipher_tdes_wrap_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_block.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_ccm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_ccm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_gcm.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_gcm_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/ciphers/ciphercommon_hw.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/blake2_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/blake2b_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/blake2s_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/digestcommon.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/md5_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/md5_sha1_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/null_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/ripemd_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/sha2_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/sha3_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/digests/sm3_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_der2key.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_epki2pki.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_msblob2key.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_pem2der.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_pvk2key.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/decode_spki2typespki.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/encode_key2any.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/encode_key2blob.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/encode_key2ms.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/encode_key2text.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/encode_decode/endecoder_common.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/exchange/dh_exch.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/exchange/ecdh_exch.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/exchange/ecx_exch.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/exchange/kdf_exch.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/argon2.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/hkdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/hmacdrbg_kdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/kbkdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/krb5kdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/pbkdf1.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/pbkdf2.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/pbkdf2_fips.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/pkcs12kdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/pvkkdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/scrypt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/sshkdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/sskdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/tls1_prf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kdfs/x942kdf.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kem/ec_kem.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kem/ecx_kem.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kem/kem_util.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/kem/rsa_kem.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/dh_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/dsa_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/ec_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/ecx_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/kdf_legacy_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/mac_legacy_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/keymgmt/rsa_kmgmt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/blake2b_mac.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/blake2s_mac.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/cmac_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/gmac_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/hmac_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/kmac_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/poly1305_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/macs/siphash_prov.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/crngt.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/drbg.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/drbg_ctr.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/drbg_hash.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/drbg_hmac.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/seed_src.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/seeding/rand_cpu_x86.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/seeding/rand_tsc.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/seeding/rand_unix.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/seeding/rand_win.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/rands/test_rng.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/dsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/ecdsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/eddsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/mac_legacy_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/rsa_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/signature/sm2_sig.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/storemgmt/file_store.c
    ${PROJECT_SOURCE_DIR}/src/providers/implementations/storemgmt/file_store_any2obj.c
    ${PROJECT_SOURCE_DIR}/src/providers/legacyprov.c
    ${PROJECT_SOURCE_DIR}/src/providers/nullprov.c
    ${PROJECT_SOURCE_DIR}/src/providers/prov_running.c
    ${PROJECT_SOURCE_DIR}/src/ssl/bio_ssl.c
    ${PROJECT_SOURCE_DIR}/src/ssl/d1_lib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/d1_msg.c
    ${PROJECT_SOURCE_DIR}/src/ssl/d1_srtp.c
    ${PROJECT_SOURCE_DIR}/src/ssl/event_queue.c
    ${PROJECT_SOURCE_DIR}/src/ssl/methods.c
    ${PROJECT_SOURCE_DIR}/src/ssl/pqueue.c
    ${PROJECT_SOURCE_DIR}/src/ssl/priority_queue.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/cc_newreno.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/json_enc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/qlog.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/qlog_event_helpers.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_ackm.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_cfq.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_channel.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_demux.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_engine.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_fc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_fifd.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_impl.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_lcidm.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_method.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_port.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_rcidm.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_reactor.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_record_rx.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_record_shared.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_record_tx.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_record_util.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_rstream.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_rx_depack.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_sf_list.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_srt_gen.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_srtm.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_sstream.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_statm.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_stream_map.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_thread_assist.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_tls.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_trace.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_tserver.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_txp.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_txpim.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_types.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_wire.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/quic_wire_pkt.c
    ${PROJECT_SOURCE_DIR}/src/ssl/quic/uint_set.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/dtls_meth.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/ssl3_cbc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/ssl3_meth.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tls13_meth.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tls1_meth.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tls_common.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tls_multib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tls_pad.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/methods/tlsany_meth.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/rec_layer_d1.c
    ${PROJECT_SOURCE_DIR}/src/ssl/record/rec_layer_s3.c
    ${PROJECT_SOURCE_DIR}/src/ssl/rio/poll_immediate.c
    ${PROJECT_SOURCE_DIR}/src/ssl/s3_enc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/s3_lib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/s3_msg.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_asn1.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_cert.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_cert_comp.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_ciph.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_conf.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_err.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_err_legacy.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_init.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_lib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_mcnf.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_rsa.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_rsa_legacy.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_sess.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_stat.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_txt.c
    ${PROJECT_SOURCE_DIR}/src/ssl/ssl_utst.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/extensions.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/extensions_clnt.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/extensions_cust.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/extensions_srvr.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/statem.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/statem_clnt.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/statem_dtls.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/statem_lib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/statem/statem_srvr.c
    ${PROJECT_SOURCE_DIR}/src/ssl/t1_enc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/t1_lib.c
    ${PROJECT_SOURCE_DIR}/src/ssl/t1_trce.c
    ${PROJECT_SOURCE_DIR}/src/ssl/tls13_enc.c
    ${PROJECT_SOURCE_DIR}/src/ssl/tls_depr.c
    ${PROJECT_SOURCE_DIR}/src/ssl/tls_srp.c
)

add_definitions(-DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSTATIC_LEGACY)
