add_definitions(-DV8_TARGET_ARCH_X64)

set(src_list
	${PROJECT_SOURCE_DIR}/gen/64/src/regexp/special-case.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/class-debug-readers.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/class-verifiers.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/debug-macros.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/enum-verifiers.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/exported-macros-assembler.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/factory.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/objects-printer.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/aggregate-error-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/aggregate-error-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-at-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-at-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-concat-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-concat-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-copywithin-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-copywithin-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-every-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-every-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-filter-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-filter-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-find-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-find-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findindex-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findindex-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findlast-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findlast-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findlastindex-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-findlastindex-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-foreach-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-foreach-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-from-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-from-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-isarray-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-isarray-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-join-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-join-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-lastindexof-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-lastindexof-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-map-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-map-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-of-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-of-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reduce-right-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reduce-right-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reduce-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reduce-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reverse-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-reverse-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-shift-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-shift-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-slice-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-slice-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-some-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-some-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-splice-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-splice-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-reversed-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-reversed-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-sorted-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-sorted-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-spliced-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-to-spliced-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-unshift-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-unshift-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-with-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/array-with-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/arraybuffer-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/arraybuffer-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/base-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/base-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/boolean-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/boolean-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/builtins-bigint-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/builtins-bigint-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/builtins-string-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/builtins-string-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/cast-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/cast-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/collections-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/collections-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/console-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/console-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/constructor-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/constructor-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/conversion-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/conversion-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/convert-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/convert-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/data-view-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/data-view-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/finalization-registry-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/finalization-registry-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/frame-arguments-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/frame-arguments-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/frames-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/frames-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/function-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/function-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/growable-fixed-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/growable-fixed-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/ic-callable-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/ic-callable-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/ic-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/ic-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/internal-coverage-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/internal-coverage-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/internal-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/internal-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-from-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-from-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-helpers-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-helpers-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/math-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/math-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/number-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/number-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/object-fromentries-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/object-fromentries-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/object-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/object-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-abstract-operations-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-abstract-operations-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-all-element-closure-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-all-element-closure-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-all-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-all-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-any-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-any-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-constructor-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-constructor-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-finally-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-finally-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-jobs-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-jobs-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-misc-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-misc-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-race-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-race-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-reaction-job-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-reaction-job-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-resolve-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-resolve-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-then-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/promise-then-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-constructor-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-constructor-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-delete-property-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-delete-property-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-get-property-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-get-property-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-get-prototype-of-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-get-prototype-of-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-has-property-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-has-property-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-is-extensible-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-is-extensible-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-prevent-extensions-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-prevent-extensions-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-revocable-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-revocable-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-revoke-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-revoke-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-set-property-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-set-property-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-set-prototype-of-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-set-prototype-of-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/proxy-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/reflect-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/reflect-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-exec-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-exec-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-match-all-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-match-all-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-match-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-match-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-replace-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-replace-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-search-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-search-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-source-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-source-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-split-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-split-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-test-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-test-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/regexp-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-at-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-at-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-endswith-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-endswith-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-html-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-html-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-includes-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-includes-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-indexof-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-indexof-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-iswellformed-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-iswellformed-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-match-search-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-match-search-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-pad-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-pad-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-repeat-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-repeat-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-replaceall-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-replaceall-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-slice-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-slice-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-startswith-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-startswith-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-substr-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-substr-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-substring-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-substring-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-towellformed-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-towellformed-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-trim-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/string-trim-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/symbol-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/symbol-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/torque-internal-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/torque-internal-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-at-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-at-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-createtypedarray-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-createtypedarray-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-entries-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-entries-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-every-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-every-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-filter-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-filter-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-find-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-find-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findindex-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findindex-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findlast-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findlast-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findlastindex-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-findlastindex-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-foreach-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-foreach-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-from-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-from-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-keys-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-keys-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-of-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-of-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-reduce-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-reduce-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-reduceright-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-reduceright-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-set-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-set-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-slice-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-slice-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-some-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-some-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-sort-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-sort-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-subarray-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-subarray-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-to-reversed-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-to-reversed-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-to-sorted-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-to-sorted-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-values-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-values-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-with-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/typed-array-with-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/wasm-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/wasm-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/weak-ref-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/builtins/weak-ref-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/debug/debug-wasm-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/debug/debug-wasm-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/ic/handler-configuration-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/ic/handler-configuration-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/allocation-site-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/allocation-site-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/api-callbacks-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/api-callbacks-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/arguments-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/arguments-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/bigint-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/bigint-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/bytecode-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/bytecode-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/call-site-info-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/call-site-info-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/cell-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/cell-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/contexts-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/contexts-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/data-handler-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/data-handler-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/debug-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/debug-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/descriptor-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/descriptor-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/embedder-data-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/embedder-data-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/feedback-cell-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/feedback-cell-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/feedback-vector-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/feedback-vector-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/fixed-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/fixed-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/foreign-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/foreign-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/free-space-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/free-space-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/heap-number-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/heap-number-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/heap-object-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/heap-object-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/hole-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/hole-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/intl-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/intl-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-array-buffer-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-array-buffer-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-atomics-synchronization-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-atomics-synchronization-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-break-iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-break-iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collection-iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collection-iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collection-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-collection-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-date-time-format-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-date-time-format-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-display-names-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-display-names-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-duration-format-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-duration-format-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-function-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-function-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-generator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-generator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-iterator-helpers-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-iterator-helpers-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-list-format-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-list-format-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-locale-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-locale-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-number-format-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-number-format-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-plural-rules-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-plural-rules-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-promise-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-promise-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-proxy-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-proxy-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-raw-json-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-raw-json-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-regexp-string-iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-regexp-string-iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-regexp-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-regexp-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-relative-time-format-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-relative-time-format-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segment-iterator-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segment-iterator-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segmenter-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segmenter-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segments-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-segments-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-shadow-realm-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-shadow-realm-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-shared-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-shared-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-struct-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-struct-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-temporal-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-temporal-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-weak-refs-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/js-weak-refs-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/literal-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/literal-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/map-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/map-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/megadom-handler-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/megadom-handler-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/microtask-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/microtask-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/module-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/module-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/name-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/name-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/oddball-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/oddball-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/ordered-hash-table-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/ordered-hash-table-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/primitive-heap-object-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/primitive-heap-object-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/promise-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/promise-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-array-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-array-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-cell-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-cell-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-descriptor-object-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/property-descriptor-object-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/prototype-info-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/prototype-info-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/regexp-match-info-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/regexp-match-info-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/scope-info-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/scope-info-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/script-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/script-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/shared-function-info-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/shared-function-info-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/source-text-module-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/source-text-module-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/string-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/string-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/struct-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/struct-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/swiss-hash-table-helpers-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/swiss-hash-table-helpers-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/swiss-name-dictionary-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/swiss-name-dictionary-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/synthetic-module-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/synthetic-module-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/template-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/template-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/templates-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/templates-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/torque-defined-classes-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/torque-defined-classes-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/turbofan-types-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/turbofan-types-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/turboshaft-types-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/objects/turboshaft-types-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/wasm/wasm-objects-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/src/wasm/wasm-objects-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/test/torque/test-torque-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/test/torque/test-torque-tq.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/third_party/v8/builtins/array-sort-tq-csa.cc
	${PROJECT_SOURCE_DIR}/gen/64/torque-generated/third_party/v8/builtins/array-sort-tq.cc
	${PROJECT_SOURCE_DIR}/patch/snapshot/embedded-amd64-Linux.S
	${PROJECT_SOURCE_DIR}/patch/snapshot/snapshot-amd64-Linux.cc
	${PROJECT_SOURCE_DIR}/patch/src/base/platform/condition-variable.cc
	${PROJECT_SOURCE_DIR}/patch/src/base/platform/mutex.cc
	${PROJECT_SOURCE_DIR}/patch/src/base/platform/platform-fiber.cc
	${PROJECT_SOURCE_DIR}/patch/src/base/platform/platform.cc
	${PROJECT_SOURCE_DIR}/patch/src/base/platform/semaphore.cc
	${PROJECT_SOURCE_DIR}/patch/src/builtin/mulodi4.c
	${PROJECT_SOURCE_DIR}/patch/src/pthread_jit_write_protect_np.cc
	${PROJECT_SOURCE_DIR}/src/api/api-arguments.cc
	${PROJECT_SOURCE_DIR}/src/api/api-natives.cc
	${PROJECT_SOURCE_DIR}/src/api/api.cc
	${PROJECT_SOURCE_DIR}/src/asmjs/asm-js.cc
	${PROJECT_SOURCE_DIR}/src/asmjs/asm-parser.cc
	${PROJECT_SOURCE_DIR}/src/asmjs/asm-scanner.cc
	${PROJECT_SOURCE_DIR}/src/asmjs/asm-types.cc
	${PROJECT_SOURCE_DIR}/src/ast/ast-function-literal-id-reindexer.cc
	${PROJECT_SOURCE_DIR}/src/ast/ast-value-factory.cc
	${PROJECT_SOURCE_DIR}/src/ast/ast.cc
	${PROJECT_SOURCE_DIR}/src/ast/modules.cc
	${PROJECT_SOURCE_DIR}/src/ast/prettyprinter.cc
	${PROJECT_SOURCE_DIR}/src/ast/scopes.cc
	${PROJECT_SOURCE_DIR}/src/ast/source-range-ast-visitor.cc
	${PROJECT_SOURCE_DIR}/src/ast/variables.cc
	${PROJECT_SOURCE_DIR}/src/base/bits.cc
	${PROJECT_SOURCE_DIR}/src/base/bounded-page-allocator.cc
	${PROJECT_SOURCE_DIR}/src/base/cpu.cc
	${PROJECT_SOURCE_DIR}/src/base/debug/stack_trace.cc
	${PROJECT_SOURCE_DIR}/src/base/debug/stack_trace_android.cc
	${PROJECT_SOURCE_DIR}/src/base/division-by-constant.cc
	${PROJECT_SOURCE_DIR}/src/base/emulated-virtual-address-subspace.cc
	${PROJECT_SOURCE_DIR}/src/base/file-utils.cc
	${PROJECT_SOURCE_DIR}/src/base/ieee754.cc
	${PROJECT_SOURCE_DIR}/src/base/logging.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/bignum-dtoa.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/bignum.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/cached-powers.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/diy-fp.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/dtoa.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/fast-dtoa.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/fixed-dtoa.cc
	${PROJECT_SOURCE_DIR}/src/base/numbers/strtod.cc
	${PROJECT_SOURCE_DIR}/src/base/once.cc
	${PROJECT_SOURCE_DIR}/src/base/page-allocator.cc
	${PROJECT_SOURCE_DIR}/src/base/platform/memory-protection-key.cc
	${PROJECT_SOURCE_DIR}/src/base/platform/platform-linux.cc
	${PROJECT_SOURCE_DIR}/src/base/platform/platform-posix-time.cc
	${PROJECT_SOURCE_DIR}/src/base/platform/time.cc
	${PROJECT_SOURCE_DIR}/src/base/region-allocator.cc
	${PROJECT_SOURCE_DIR}/src/base/sanitizer/lsan-page-allocator.cc
	${PROJECT_SOURCE_DIR}/src/base/sanitizer/lsan-virtual-address-space.cc
	${PROJECT_SOURCE_DIR}/src/base/strings.cc
	${PROJECT_SOURCE_DIR}/src/base/sys-info.cc
	${PROJECT_SOURCE_DIR}/src/base/utils/random-number-generator.cc
	${PROJECT_SOURCE_DIR}/src/base/virtual-address-space-page-allocator.cc
	${PROJECT_SOURCE_DIR}/src/base/virtual-address-space.cc
	${PROJECT_SOURCE_DIR}/src/base/vlq-base64.cc
	${PROJECT_SOURCE_DIR}/src/baseline/baseline-batch-compiler.cc
	${PROJECT_SOURCE_DIR}/src/baseline/baseline-compiler.cc
	${PROJECT_SOURCE_DIR}/src/baseline/baseline.cc
	${PROJECT_SOURCE_DIR}/src/baseline/bytecode-offset-iterator.cc
	${PROJECT_SOURCE_DIR}/src/bigint/bigint-internal.cc
	${PROJECT_SOURCE_DIR}/src/bigint/bitwise.cc
	${PROJECT_SOURCE_DIR}/src/bigint/div-barrett.cc
	${PROJECT_SOURCE_DIR}/src/bigint/div-burnikel.cc
	${PROJECT_SOURCE_DIR}/src/bigint/div-helpers.cc
	${PROJECT_SOURCE_DIR}/src/bigint/div-schoolbook.cc
	${PROJECT_SOURCE_DIR}/src/bigint/fromstring.cc
	${PROJECT_SOURCE_DIR}/src/bigint/mul-fft.cc
	${PROJECT_SOURCE_DIR}/src/bigint/mul-karatsuba.cc
	${PROJECT_SOURCE_DIR}/src/bigint/mul-schoolbook.cc
	${PROJECT_SOURCE_DIR}/src/bigint/mul-toom.cc
	${PROJECT_SOURCE_DIR}/src/bigint/tostring.cc
	${PROJECT_SOURCE_DIR}/src/bigint/vector-arithmetic.cc
	${PROJECT_SOURCE_DIR}/src/builtins/accessors.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-api.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-array-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-array.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-arraybuffer.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-async-function-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-async-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-async-generator-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-async-iterator-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-async-module.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-atomics-synchronization.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-bigint-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-bigint.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-call-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-callsite.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-collections-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-collections.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-console.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-constructor-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-conversion-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-dataview.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-date-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-date.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-error.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-function.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-generator-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-global-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-global.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-handler-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-ic-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-internal-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-internal.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-interpreter-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-intl-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-intl.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-iterator-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-json.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-lazy-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-microtask-queue-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-number-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-number.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-object-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-object.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-promise-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-proxy-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-reflect.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-regexp-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-regexp.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-shadow-realm-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-shadow-realm.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-shared-array.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-sharedarraybuffer-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-sharedarraybuffer.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-string-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-string.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-struct.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-symbol.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-temporal-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-temporal.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-trace.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-typed-array-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-typed-array.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-wasm-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins-weak-refs.cc
	${PROJECT_SOURCE_DIR}/src/builtins/builtins.cc
	${PROJECT_SOURCE_DIR}/src/builtins/constants-table-builder.cc
	${PROJECT_SOURCE_DIR}/src/builtins/growable-fixed-array-gen.cc
	${PROJECT_SOURCE_DIR}/src/builtins/profile-data-reader.cc
	${PROJECT_SOURCE_DIR}/src/builtins/setup-builtins-internal.cc
	${PROJECT_SOURCE_DIR}/src/builtins/x64/builtins-x64.cc
	${PROJECT_SOURCE_DIR}/src/codegen/aligned-slot-allocator.cc
	${PROJECT_SOURCE_DIR}/src/codegen/assembler.cc
	${PROJECT_SOURCE_DIR}/src/codegen/bailout-reason.cc
	${PROJECT_SOURCE_DIR}/src/codegen/code-comments.cc
	${PROJECT_SOURCE_DIR}/src/codegen/code-desc.cc
	${PROJECT_SOURCE_DIR}/src/codegen/code-factory.cc
	${PROJECT_SOURCE_DIR}/src/codegen/code-reference.cc
	${PROJECT_SOURCE_DIR}/src/codegen/code-stub-assembler.cc
	${PROJECT_SOURCE_DIR}/src/codegen/compilation-cache.cc
	${PROJECT_SOURCE_DIR}/src/codegen/compiler.cc
	${PROJECT_SOURCE_DIR}/src/codegen/constant-pool.cc
	${PROJECT_SOURCE_DIR}/src/codegen/external-reference-encoder.cc
	${PROJECT_SOURCE_DIR}/src/codegen/external-reference-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/external-reference.cc
	${PROJECT_SOURCE_DIR}/src/codegen/flush-instruction-cache.cc
	${PROJECT_SOURCE_DIR}/src/codegen/handler-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/interface-descriptors.cc
	${PROJECT_SOURCE_DIR}/src/codegen/machine-type.cc
	${PROJECT_SOURCE_DIR}/src/codegen/macro-assembler-base.cc
	${PROJECT_SOURCE_DIR}/src/codegen/maglev-safepoint-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/optimized-compilation-info.cc
	${PROJECT_SOURCE_DIR}/src/codegen/pending-optimization-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/register-configuration.cc
	${PROJECT_SOURCE_DIR}/src/codegen/reloc-info.cc
	${PROJECT_SOURCE_DIR}/src/codegen/safepoint-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.cc
	${PROJECT_SOURCE_DIR}/src/codegen/source-position-table.cc
	${PROJECT_SOURCE_DIR}/src/codegen/source-position.cc
	${PROJECT_SOURCE_DIR}/src/codegen/string-constants.cc
	${PROJECT_SOURCE_DIR}/src/codegen/tick-counter.cc
	${PROJECT_SOURCE_DIR}/src/codegen/tnode.cc
	${PROJECT_SOURCE_DIR}/src/codegen/unoptimized-compilation-info.cc
	${PROJECT_SOURCE_DIR}/src/codegen/x64/assembler-x64.cc
	${PROJECT_SOURCE_DIR}/src/codegen/x64/cpu-x64.cc
	${PROJECT_SOURCE_DIR}/src/codegen/x64/macro-assembler-x64.cc
	${PROJECT_SOURCE_DIR}/src/common/assert-scope.cc
	${PROJECT_SOURCE_DIR}/src/common/code-memory-access.cc
	${PROJECT_SOURCE_DIR}/src/common/ptr-compr.cc
	${PROJECT_SOURCE_DIR}/src/compiler-dispatcher/lazy-compile-dispatcher.cc
	${PROJECT_SOURCE_DIR}/src/compiler-dispatcher/optimizing-compile-dispatcher.cc
	${PROJECT_SOURCE_DIR}/src/compiler/access-builder.cc
	${PROJECT_SOURCE_DIR}/src/compiler/access-info.cc
	${PROJECT_SOURCE_DIR}/src/compiler/add-type-assertions-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/all-nodes.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/bitcast-elider.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/code-generator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/frame-elider.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/gap-resolver.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/instruction-scheduler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/instruction-selector.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/instruction.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/jump-threading.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/mid-tier-register-allocator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/move-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/register-allocator-verifier.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/register-allocator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/spill-placer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/x64/code-generator-x64.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/x64/instruction-scheduler-x64.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/x64/instruction-selector-x64.cc
	${PROJECT_SOURCE_DIR}/src/compiler/backend/x64/unwinding-info-writer-x64.cc
	${PROJECT_SOURCE_DIR}/src/compiler/basic-block-instrumentor.cc
	${PROJECT_SOURCE_DIR}/src/compiler/branch-condition-duplicator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/branch-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/bytecode-analysis.cc
	${PROJECT_SOURCE_DIR}/src/compiler/bytecode-graph-builder.cc
	${PROJECT_SOURCE_DIR}/src/compiler/bytecode-liveness-map.cc
	${PROJECT_SOURCE_DIR}/src/compiler/c-linkage.cc
	${PROJECT_SOURCE_DIR}/src/compiler/checkpoint-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/code-assembler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/common-node-cache.cc
	${PROJECT_SOURCE_DIR}/src/compiler/common-operator-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/common-operator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/compilation-dependencies.cc
	${PROJECT_SOURCE_DIR}/src/compiler/compiler-source-position-table.cc
	${PROJECT_SOURCE_DIR}/src/compiler/constant-folding-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/control-equivalence.cc
	${PROJECT_SOURCE_DIR}/src/compiler/control-flow-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/csa-load-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/dead-code-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/decompression-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/effect-control-linearizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/escape-analysis-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/escape-analysis.cc
	${PROJECT_SOURCE_DIR}/src/compiler/fast-api-calls.cc
	${PROJECT_SOURCE_DIR}/src/compiler/feedback-source.cc
	${PROJECT_SOURCE_DIR}/src/compiler/frame-states.cc
	${PROJECT_SOURCE_DIR}/src/compiler/frame.cc
	${PROJECT_SOURCE_DIR}/src/compiler/graph-assembler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/graph-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/graph-trimmer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/graph-visualizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/graph.cc
	${PROJECT_SOURCE_DIR}/src/compiler/heap-refs.cc
	${PROJECT_SOURCE_DIR}/src/compiler/int64-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-call-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-context-specialization.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-create-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-generic-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-graph.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-heap-broker.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-inlining-heuristic.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-inlining.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-intrinsic-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-native-context-specialization.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-operator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-type-hint-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/js-typed-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/late-escape-analysis.cc
	${PROJECT_SOURCE_DIR}/src/compiler/linear-scheduler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/linkage.cc
	${PROJECT_SOURCE_DIR}/src/compiler/load-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/loop-analysis.cc
	${PROJECT_SOURCE_DIR}/src/compiler/loop-peeling.cc
	${PROJECT_SOURCE_DIR}/src/compiler/loop-unrolling.cc
	${PROJECT_SOURCE_DIR}/src/compiler/loop-variable-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/machine-graph-verifier.cc
	${PROJECT_SOURCE_DIR}/src/compiler/machine-graph.cc
	${PROJECT_SOURCE_DIR}/src/compiler/machine-operator-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/machine-operator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/map-inference.cc
	${PROJECT_SOURCE_DIR}/src/compiler/memory-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/memory-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node-marker.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node-matchers.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node-observer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node-origin-table.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node-properties.cc
	${PROJECT_SOURCE_DIR}/src/compiler/node.cc
	${PROJECT_SOURCE_DIR}/src/compiler/opcodes.cc
	${PROJECT_SOURCE_DIR}/src/compiler/operation-typer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/operator-properties.cc
	${PROJECT_SOURCE_DIR}/src/compiler/operator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/osr.cc
	${PROJECT_SOURCE_DIR}/src/compiler/pair-load-store-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/pipeline-statistics.cc
	${PROJECT_SOURCE_DIR}/src/compiler/pipeline.cc
	${PROJECT_SOURCE_DIR}/src/compiler/property-access-builder.cc
	${PROJECT_SOURCE_DIR}/src/compiler/raw-machine-assembler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/redundancy-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/refs-map.cc
	${PROJECT_SOURCE_DIR}/src/compiler/representation-change.cc
	${PROJECT_SOURCE_DIR}/src/compiler/schedule.cc
	${PROJECT_SOURCE_DIR}/src/compiler/scheduler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/select-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/simplified-lowering-verifier.cc
	${PROJECT_SOURCE_DIR}/src/compiler/simplified-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/simplified-operator-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/simplified-operator.cc
	${PROJECT_SOURCE_DIR}/src/compiler/state-values-utils.cc
	${PROJECT_SOURCE_DIR}/src/compiler/store-store-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/string-builder-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turbofan-disabled.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turbofan-enabled.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/assembler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/build-graph-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/dead-code-elimination-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/decompression-optimization-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/decompression-optimization.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/graph-builder.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/graph-visualizer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/graph.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/late-escape-analysis-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/machine-lowering-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/memory-optimization-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/operations.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/optimization-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/optimize-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/pretenuring-propagation-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/recreate-schedule-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/recreate-schedule.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/representations.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/simplify-tf-loops.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/store-store-elimination-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/type-assertions-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/type-parser.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/typed-optimizations-phase.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/typer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/types.cc
	${PROJECT_SOURCE_DIR}/src/compiler/turboshaft/utils.cc
	${PROJECT_SOURCE_DIR}/src/compiler/type-cache.cc
	${PROJECT_SOURCE_DIR}/src/compiler/type-narrowing-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/typed-optimization.cc
	${PROJECT_SOURCE_DIR}/src/compiler/typer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/types.cc
	${PROJECT_SOURCE_DIR}/src/compiler/value-numbering-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/verifier.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-address-reassociation.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-call-descriptors.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-compiler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-escape-analysis.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-gc-lowering.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-gc-operator-reducer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-graph-assembler.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-inlining-into-js.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-inlining.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-load-elimination.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-loop-peeling.cc
	${PROJECT_SOURCE_DIR}/src/compiler/wasm-typer.cc
	${PROJECT_SOURCE_DIR}/src/compiler/zone-stats.cc
	${PROJECT_SOURCE_DIR}/src/date/date.cc
	${PROJECT_SOURCE_DIR}/src/date/dateparser.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-coverage.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-evaluate.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-frames.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-interface.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-property-iterator.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-scope-iterator.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-scopes.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-stack-trace-iterator.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug-wasm-objects.cc
	${PROJECT_SOURCE_DIR}/src/debug/debug.cc
	${PROJECT_SOURCE_DIR}/src/debug/liveedit-diff.cc
	${PROJECT_SOURCE_DIR}/src/debug/liveedit.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/deoptimize-reason.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/deoptimized-frame-info.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/deoptimizer-cfi-builtins.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/deoptimizer.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/materialized-object-store.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/translated-state.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/translation-array.cc
	${PROJECT_SOURCE_DIR}/src/deoptimizer/x64/deoptimizer-x64.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/basic-block-profiler.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/compilation-statistics.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/disassembler.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/eh-frame.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/gdb-jit.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/objects-debug.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/objects-printer.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/perf-jit.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/unwinder.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/x64/disasm-x64.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/x64/eh-frame-x64.cc
	${PROJECT_SOURCE_DIR}/src/diagnostics/x64/unwinder-x64.cc
	${PROJECT_SOURCE_DIR}/src/execution/arguments.cc
	${PROJECT_SOURCE_DIR}/src/execution/clobber-registers.cc
	${PROJECT_SOURCE_DIR}/src/execution/embedder-state.cc
	${PROJECT_SOURCE_DIR}/src/execution/encoded-c-signature.cc
	${PROJECT_SOURCE_DIR}/src/execution/execution.cc
	${PROJECT_SOURCE_DIR}/src/execution/frames.cc
	${PROJECT_SOURCE_DIR}/src/execution/futex-emulation.cc
	${PROJECT_SOURCE_DIR}/src/execution/interrupts-scope.cc
	${PROJECT_SOURCE_DIR}/src/execution/isolate.cc
	${PROJECT_SOURCE_DIR}/src/execution/local-isolate.cc
	${PROJECT_SOURCE_DIR}/src/execution/messages.cc
	${PROJECT_SOURCE_DIR}/src/execution/microtask-queue.cc
	${PROJECT_SOURCE_DIR}/src/execution/protectors.cc
	${PROJECT_SOURCE_DIR}/src/execution/simulator-base.cc
	${PROJECT_SOURCE_DIR}/src/execution/stack-guard.cc
	${PROJECT_SOURCE_DIR}/src/execution/thread-id.cc
	${PROJECT_SOURCE_DIR}/src/execution/thread-local-top.cc
	${PROJECT_SOURCE_DIR}/src/execution/tiering-manager.cc
	${PROJECT_SOURCE_DIR}/src/execution/v8threads.cc
	${PROJECT_SOURCE_DIR}/src/execution/x64/frame-constants-x64.cc
	${PROJECT_SOURCE_DIR}/src/extensions/cputracemark-extension.cc
	${PROJECT_SOURCE_DIR}/src/extensions/externalize-string-extension.cc
	${PROJECT_SOURCE_DIR}/src/extensions/gc-extension.cc
	${PROJECT_SOURCE_DIR}/src/extensions/ignition-statistics-extension.cc
	${PROJECT_SOURCE_DIR}/src/extensions/statistics-extension.cc
	${PROJECT_SOURCE_DIR}/src/extensions/trigger-failure-extension.cc
	${PROJECT_SOURCE_DIR}/src/flags/flags.cc
	${PROJECT_SOURCE_DIR}/src/handles/global-handles.cc
	${PROJECT_SOURCE_DIR}/src/handles/handles.cc
	${PROJECT_SOURCE_DIR}/src/handles/local-handles.cc
	${PROJECT_SOURCE_DIR}/src/handles/persistent-handles.cc
	${PROJECT_SOURCE_DIR}/src/handles/shared-object-conveyor-handles.cc
	${PROJECT_SOURCE_DIR}/src/handles/traced-handles.cc
	${PROJECT_SOURCE_DIR}/src/heap/allocation-observer.cc
	${PROJECT_SOURCE_DIR}/src/heap/array-buffer-sweeper.cc
	${PROJECT_SOURCE_DIR}/src/heap/base-space.cc
	${PROJECT_SOURCE_DIR}/src/heap/base/active-system-pages.cc
	${PROJECT_SOURCE_DIR}/src/heap/base/asm/x64/push_registers_asm.cc
	${PROJECT_SOURCE_DIR}/src/heap/base/stack.cc
	${PROJECT_SOURCE_DIR}/src/heap/base/worklist.cc
	${PROJECT_SOURCE_DIR}/src/heap/basic-memory-chunk.cc
	${PROJECT_SOURCE_DIR}/src/heap/code-object-registry.cc
	${PROJECT_SOURCE_DIR}/src/heap/code-range.cc
	${PROJECT_SOURCE_DIR}/src/heap/code-stats.cc
	${PROJECT_SOURCE_DIR}/src/heap/collection-barrier.cc
	${PROJECT_SOURCE_DIR}/src/heap/combined-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/concurrent-allocator.cc
	${PROJECT_SOURCE_DIR}/src/heap/concurrent-marking.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/cpp-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/cpp-snapshot.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/cross-heap-remembered-set.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/unified-heap-marking-state.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/unified-heap-marking-verifier.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc-js/unified-heap-marking-visitor.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/allocation.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/caged-heap-local-data.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/compaction-worklists.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/compactor.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/concurrent-marker.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/explicit-management.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/free-list.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/gc-info-table.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/gc-info.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/gc-invoker.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-base.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-consistency.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-growing.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-object-header.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-page.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-space.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-state.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap-statistics-collector.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/incremental-marking-schedule.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/liveness-broker.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/logging.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/marker.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/marking-state.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/marking-verifier.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/marking-visitor.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/marking-worklists.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/member-storage.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/memory.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/name-trait.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/object-allocator.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/object-size-trait.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/page-memory.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/persistent-node.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/platform.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/pointer-policies.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/prefinalizer-handler.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/process-heap-statistics.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/process-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/raw-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/remembered-set.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/stats-collector.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/sweeper.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/testing.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/trace-trait.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/virtual-memory.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/visitor.cc
	${PROJECT_SOURCE_DIR}/src/heap/cppgc/write-barrier.cc
	${PROJECT_SOURCE_DIR}/src/heap/ephemeron-remembered-set.cc
	${PROJECT_SOURCE_DIR}/src/heap/evacuation-verifier.cc
	${PROJECT_SOURCE_DIR}/src/heap/factory-base.cc
	${PROJECT_SOURCE_DIR}/src/heap/factory.cc
	${PROJECT_SOURCE_DIR}/src/heap/finalization-registry-cleanup-task.cc
	${PROJECT_SOURCE_DIR}/src/heap/free-list.cc
	${PROJECT_SOURCE_DIR}/src/heap/gc-idle-time-handler.cc
	${PROJECT_SOURCE_DIR}/src/heap/gc-tracer.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap-allocator.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap-controller.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap-layout-tracer.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap-verifier.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap-write-barrier.cc
	${PROJECT_SOURCE_DIR}/src/heap/heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/incremental-marking-job.cc
	${PROJECT_SOURCE_DIR}/src/heap/incremental-marking.cc
	${PROJECT_SOURCE_DIR}/src/heap/index-generator.cc
	${PROJECT_SOURCE_DIR}/src/heap/large-spaces.cc
	${PROJECT_SOURCE_DIR}/src/heap/local-factory.cc
	${PROJECT_SOURCE_DIR}/src/heap/local-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/mark-compact.cc
	${PROJECT_SOURCE_DIR}/src/heap/marking-barrier.cc
	${PROJECT_SOURCE_DIR}/src/heap/marking-worklist.cc
	${PROJECT_SOURCE_DIR}/src/heap/marking.cc
	${PROJECT_SOURCE_DIR}/src/heap/memory-allocator.cc
	${PROJECT_SOURCE_DIR}/src/heap/memory-chunk-layout.cc
	${PROJECT_SOURCE_DIR}/src/heap/memory-chunk.cc
	${PROJECT_SOURCE_DIR}/src/heap/memory-measurement.cc
	${PROJECT_SOURCE_DIR}/src/heap/memory-reducer.cc
	${PROJECT_SOURCE_DIR}/src/heap/minor-gc-job.cc
	${PROJECT_SOURCE_DIR}/src/heap/new-spaces.cc
	${PROJECT_SOURCE_DIR}/src/heap/object-stats.cc
	${PROJECT_SOURCE_DIR}/src/heap/objects-visiting.cc
	${PROJECT_SOURCE_DIR}/src/heap/paged-spaces.cc
	${PROJECT_SOURCE_DIR}/src/heap/pretenuring-handler.cc
	${PROJECT_SOURCE_DIR}/src/heap/read-only-heap.cc
	${PROJECT_SOURCE_DIR}/src/heap/read-only-spaces.cc
	${PROJECT_SOURCE_DIR}/src/heap/reference-summarizer.cc
	${PROJECT_SOURCE_DIR}/src/heap/safepoint.cc
	${PROJECT_SOURCE_DIR}/src/heap/scavenger.cc
	${PROJECT_SOURCE_DIR}/src/heap/setup-heap-internal.cc
	${PROJECT_SOURCE_DIR}/src/heap/slot-set.cc
	${PROJECT_SOURCE_DIR}/src/heap/spaces.cc
	${PROJECT_SOURCE_DIR}/src/heap/stress-scavenge-observer.cc
	${PROJECT_SOURCE_DIR}/src/heap/sweeper.cc
	${PROJECT_SOURCE_DIR}/src/heap/third-party/heap-api-stub.cc
	${PROJECT_SOURCE_DIR}/src/heap/traced-handles-marking-visitor.cc
	${PROJECT_SOURCE_DIR}/src/heap/weak-object-worklists.cc
	${PROJECT_SOURCE_DIR}/src/ic/accessor-assembler.cc
	${PROJECT_SOURCE_DIR}/src/ic/binary-op-assembler.cc
	${PROJECT_SOURCE_DIR}/src/ic/call-optimization.cc
	${PROJECT_SOURCE_DIR}/src/ic/handler-configuration.cc
	${PROJECT_SOURCE_DIR}/src/ic/ic-stats.cc
	${PROJECT_SOURCE_DIR}/src/ic/ic.cc
	${PROJECT_SOURCE_DIR}/src/ic/keyed-store-generic.cc
	${PROJECT_SOURCE_DIR}/src/ic/stub-cache.cc
	${PROJECT_SOURCE_DIR}/src/ic/unary-op-assembler.cc
	${PROJECT_SOURCE_DIR}/src/init/bootstrapper.cc
	${PROJECT_SOURCE_DIR}/src/init/icu_util.cc
	${PROJECT_SOURCE_DIR}/src/init/isolate-allocator.cc
	${PROJECT_SOURCE_DIR}/src/init/setup-isolate-deserialize.cc
	${PROJECT_SOURCE_DIR}/src/init/startup-data-util.cc
	${PROJECT_SOURCE_DIR}/src/init/v8.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-array-builder.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-array-iterator.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-array-random-iterator.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-array-writer.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-decoder.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-flags.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-generator.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-label.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-node.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-operands.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-register-optimizer.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-register.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecode-source-info.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/bytecodes.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/constant-array-builder.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/control-flow-builders.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/handler-table-builder.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/interpreter-assembler.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/interpreter-generator.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/interpreter-intrinsics-generator.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/interpreter-intrinsics.cc
	${PROJECT_SOURCE_DIR}/src/interpreter/interpreter.cc
	${PROJECT_SOURCE_DIR}/src/json/json-parser.cc
	${PROJECT_SOURCE_DIR}/src/json/json-stringifier.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/default-foreground-task-runner.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/default-job.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/default-platform.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/default-thread-isolated-allocator.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/default-worker-threads-task-runner.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/delayed-task-queue.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/task-queue.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/tracing/trace-buffer.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/tracing/trace-config.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/tracing/trace-object.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/tracing/trace-writer.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/tracing/tracing-controller.cc
	${PROJECT_SOURCE_DIR}/src/libplatform/worker-thread.cc
	${PROJECT_SOURCE_DIR}/src/libsampler/sampler.cc
	${PROJECT_SOURCE_DIR}/src/logging/counters.cc
	${PROJECT_SOURCE_DIR}/src/logging/local-logger.cc
	${PROJECT_SOURCE_DIR}/src/logging/log-file.cc
	${PROJECT_SOURCE_DIR}/src/logging/log.cc
	${PROJECT_SOURCE_DIR}/src/logging/metrics.cc
	${PROJECT_SOURCE_DIR}/src/logging/runtime-call-stats.cc
	${PROJECT_SOURCE_DIR}/src/logging/tracing-flags.cc
	${PROJECT_SOURCE_DIR}/src/numbers/conversions.cc
	${PROJECT_SOURCE_DIR}/src/numbers/math-random.cc
	${PROJECT_SOURCE_DIR}/src/objects/abstract-code.cc
	${PROJECT_SOURCE_DIR}/src/objects/backing-store.cc
	${PROJECT_SOURCE_DIR}/src/objects/bigint.cc
	${PROJECT_SOURCE_DIR}/src/objects/bytecode-array.cc
	${PROJECT_SOURCE_DIR}/src/objects/call-site-info.cc
	${PROJECT_SOURCE_DIR}/src/objects/code-kind.cc
	${PROJECT_SOURCE_DIR}/src/objects/code.cc
	${PROJECT_SOURCE_DIR}/src/objects/compilation-cache-table.cc
	${PROJECT_SOURCE_DIR}/src/objects/contexts.cc
	${PROJECT_SOURCE_DIR}/src/objects/debug-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/deoptimization-data.cc
	${PROJECT_SOURCE_DIR}/src/objects/dependent-code.cc
	${PROJECT_SOURCE_DIR}/src/objects/elements-kind.cc
	${PROJECT_SOURCE_DIR}/src/objects/elements.cc
	${PROJECT_SOURCE_DIR}/src/objects/embedder-data-array.cc
	${PROJECT_SOURCE_DIR}/src/objects/feedback-vector.cc
	${PROJECT_SOURCE_DIR}/src/objects/field-type.cc
	${PROJECT_SOURCE_DIR}/src/objects/instruction-stream.cc
	${PROJECT_SOURCE_DIR}/src/objects/intl-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-array-buffer.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-atomics-synchronization.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-break-iterator.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-collator.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-date-time-format.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-display-names.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-duration-format.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-function.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-list-format.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-locale.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-number-format.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-plural-rules.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-raw-json.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-regexp.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-relative-time-format.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-segment-iterator.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-segmenter.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-segments.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-struct.cc
	${PROJECT_SOURCE_DIR}/src/objects/js-temporal-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/keys.cc
	${PROJECT_SOURCE_DIR}/src/objects/literal-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/lookup-cache.cc
	${PROJECT_SOURCE_DIR}/src/objects/lookup.cc
	${PROJECT_SOURCE_DIR}/src/objects/managed.cc
	${PROJECT_SOURCE_DIR}/src/objects/map-updater.cc
	${PROJECT_SOURCE_DIR}/src/objects/map.cc
	${PROJECT_SOURCE_DIR}/src/objects/module.cc
	${PROJECT_SOURCE_DIR}/src/objects/object-type.cc
	${PROJECT_SOURCE_DIR}/src/objects/objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/option-utils.cc
	${PROJECT_SOURCE_DIR}/src/objects/ordered-hash-table.cc
	${PROJECT_SOURCE_DIR}/src/objects/property-descriptor.cc
	${PROJECT_SOURCE_DIR}/src/objects/property.cc
	${PROJECT_SOURCE_DIR}/src/objects/scope-info.cc
	${PROJECT_SOURCE_DIR}/src/objects/shared-function-info.cc
	${PROJECT_SOURCE_DIR}/src/objects/simd.cc
	${PROJECT_SOURCE_DIR}/src/objects/source-text-module.cc
	${PROJECT_SOURCE_DIR}/src/objects/string-comparator.cc
	${PROJECT_SOURCE_DIR}/src/objects/string-forwarding-table.cc
	${PROJECT_SOURCE_DIR}/src/objects/string-table.cc
	${PROJECT_SOURCE_DIR}/src/objects/string.cc
	${PROJECT_SOURCE_DIR}/src/objects/swiss-name-dictionary.cc
	${PROJECT_SOURCE_DIR}/src/objects/symbol-table.cc
	${PROJECT_SOURCE_DIR}/src/objects/synthetic-module.cc
	${PROJECT_SOURCE_DIR}/src/objects/tagged-impl.cc
	${PROJECT_SOURCE_DIR}/src/objects/template-objects.cc
	${PROJECT_SOURCE_DIR}/src/objects/templates.cc
	${PROJECT_SOURCE_DIR}/src/objects/transitions.cc
	${PROJECT_SOURCE_DIR}/src/objects/type-hints.cc
	${PROJECT_SOURCE_DIR}/src/objects/value-serializer.cc
	${PROJECT_SOURCE_DIR}/src/objects/visitors.cc
	${PROJECT_SOURCE_DIR}/src/parsing/func-name-inferrer.cc
	${PROJECT_SOURCE_DIR}/src/parsing/import-assertions.cc
	${PROJECT_SOURCE_DIR}/src/parsing/literal-buffer.cc
	${PROJECT_SOURCE_DIR}/src/parsing/parse-info.cc
	${PROJECT_SOURCE_DIR}/src/parsing/parser.cc
	${PROJECT_SOURCE_DIR}/src/parsing/parsing.cc
	${PROJECT_SOURCE_DIR}/src/parsing/pending-compilation-error-handler.cc
	${PROJECT_SOURCE_DIR}/src/parsing/preparse-data.cc
	${PROJECT_SOURCE_DIR}/src/parsing/preparser.cc
	${PROJECT_SOURCE_DIR}/src/parsing/rewriter.cc
	${PROJECT_SOURCE_DIR}/src/parsing/scanner-character-streams.cc
	${PROJECT_SOURCE_DIR}/src/parsing/scanner.cc
	${PROJECT_SOURCE_DIR}/src/parsing/token.cc
	${PROJECT_SOURCE_DIR}/src/profiler/allocation-tracker.cc
	${PROJECT_SOURCE_DIR}/src/profiler/cpu-profiler.cc
	${PROJECT_SOURCE_DIR}/src/profiler/heap-profiler.cc
	${PROJECT_SOURCE_DIR}/src/profiler/heap-snapshot-generator.cc
	${PROJECT_SOURCE_DIR}/src/profiler/profile-generator.cc
	${PROJECT_SOURCE_DIR}/src/profiler/profiler-listener.cc
	${PROJECT_SOURCE_DIR}/src/profiler/profiler-stats.cc
	${PROJECT_SOURCE_DIR}/src/profiler/sampling-heap-profiler.cc
	${PROJECT_SOURCE_DIR}/src/profiler/strings-storage.cc
	${PROJECT_SOURCE_DIR}/src/profiler/symbolizer.cc
	${PROJECT_SOURCE_DIR}/src/profiler/tick-sample.cc
	${PROJECT_SOURCE_DIR}/src/profiler/tracing-cpu-profiler.cc
	${PROJECT_SOURCE_DIR}/src/profiler/weak-code-registry.cc
	${PROJECT_SOURCE_DIR}/src/regexp/experimental/experimental-bytecode.cc
	${PROJECT_SOURCE_DIR}/src/regexp/experimental/experimental-compiler.cc
	${PROJECT_SOURCE_DIR}/src/regexp/experimental/experimental-interpreter.cc
	${PROJECT_SOURCE_DIR}/src/regexp/experimental/experimental.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-ast.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-bytecode-generator.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-bytecode-peephole.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-bytecodes.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-compiler-tonode.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-compiler.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-dotprinter.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-error.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-interpreter.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-macro-assembler-tracer.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-macro-assembler.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-parser.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-stack.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp-utils.cc
	${PROJECT_SOURCE_DIR}/src/regexp/regexp.cc
	${PROJECT_SOURCE_DIR}/src/regexp/x64/regexp-macro-assembler-x64.cc
	${PROJECT_SOURCE_DIR}/src/roots/roots.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-array.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-atomics.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-bigint.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-classes.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-collections.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-compiler.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-date.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-debug.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-forin.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-function.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-futex.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-generator.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-internal.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-intl.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-literals.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-module.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-numbers.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-object.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-operators.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-promise.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-proxy.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-regexp.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-scopes.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-shadow-realm.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-strings.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-symbol.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-temporal.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-test-wasm.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-test.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-trace.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-typedarray.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-wasm.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime-weak-refs.cc
	${PROJECT_SOURCE_DIR}/src/runtime/runtime.cc
	${PROJECT_SOURCE_DIR}/src/sandbox/external-pointer-table.cc
	${PROJECT_SOURCE_DIR}/src/sandbox/sandbox.cc
	${PROJECT_SOURCE_DIR}/src/sandbox/testing.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/code-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/context-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/context-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/embedded-data.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/embedded-file-writer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/platform-embedded-file-writer-aix.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/platform-embedded-file-writer-base.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/platform-embedded-file-writer-generic.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/platform-embedded-file-writer-mac.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/embedded/platform-embedded-file-writer-win.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/object-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/read-only-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/read-only-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/roots-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/serializer-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/shared-heap-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/shared-heap-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/snapshot-data.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/snapshot-source-sink.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/snapshot-utils.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/snapshot.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/startup-deserializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/startup-serializer.cc
	${PROJECT_SOURCE_DIR}/src/snapshot/static-roots-gen.cc
	${PROJECT_SOURCE_DIR}/src/strings/char-predicates.cc
	${PROJECT_SOURCE_DIR}/src/strings/string-builder.cc
	${PROJECT_SOURCE_DIR}/src/strings/string-case.cc
	${PROJECT_SOURCE_DIR}/src/strings/string-stream.cc
	${PROJECT_SOURCE_DIR}/src/strings/unicode-decoder.cc
	${PROJECT_SOURCE_DIR}/src/strings/unicode.cc
	${PROJECT_SOURCE_DIR}/src/strings/uri.cc
	${PROJECT_SOURCE_DIR}/src/tasks/cancelable-task.cc
	${PROJECT_SOURCE_DIR}/src/tasks/operations-barrier.cc
	${PROJECT_SOURCE_DIR}/src/tasks/task-utils.cc
	${PROJECT_SOURCE_DIR}/src/temporal/temporal-parser.cc
	${PROJECT_SOURCE_DIR}/src/third_party/siphash/halfsiphash.cc
	${PROJECT_SOURCE_DIR}/src/torque/cc-generator.cc
	${PROJECT_SOURCE_DIR}/src/torque/cfg.cc
	${PROJECT_SOURCE_DIR}/src/torque/class-debug-reader-generator.cc
	${PROJECT_SOURCE_DIR}/src/torque/cpp-builder.cc
	${PROJECT_SOURCE_DIR}/src/torque/csa-generator.cc
	${PROJECT_SOURCE_DIR}/src/torque/declarable.cc
	${PROJECT_SOURCE_DIR}/src/torque/declaration-visitor.cc
	${PROJECT_SOURCE_DIR}/src/torque/declarations.cc
	${PROJECT_SOURCE_DIR}/src/torque/earley-parser.cc
	${PROJECT_SOURCE_DIR}/src/torque/global-context.cc
	${PROJECT_SOURCE_DIR}/src/torque/implementation-visitor.cc
	${PROJECT_SOURCE_DIR}/src/torque/instance-type-generator.cc
	${PROJECT_SOURCE_DIR}/src/torque/instructions.cc
	${PROJECT_SOURCE_DIR}/src/torque/kythe-data.cc
	${PROJECT_SOURCE_DIR}/src/torque/ls/json-parser.cc
	${PROJECT_SOURCE_DIR}/src/torque/ls/json.cc
	${PROJECT_SOURCE_DIR}/src/torque/ls/message-handler.cc
	${PROJECT_SOURCE_DIR}/src/torque/server-data.cc
	${PROJECT_SOURCE_DIR}/src/torque/source-positions.cc
	${PROJECT_SOURCE_DIR}/src/torque/torque-code-generator.cc
	${PROJECT_SOURCE_DIR}/src/torque/torque-compiler.cc
	${PROJECT_SOURCE_DIR}/src/torque/torque-parser.cc
	${PROJECT_SOURCE_DIR}/src/torque/type-inference.cc
	${PROJECT_SOURCE_DIR}/src/torque/type-oracle.cc
	${PROJECT_SOURCE_DIR}/src/torque/type-visitor.cc
	${PROJECT_SOURCE_DIR}/src/torque/types.cc
	${PROJECT_SOURCE_DIR}/src/torque/utils.cc
	${PROJECT_SOURCE_DIR}/src/tracing/trace-categories.cc
	${PROJECT_SOURCE_DIR}/src/tracing/trace-event.cc
	${PROJECT_SOURCE_DIR}/src/tracing/traced-value.cc
	${PROJECT_SOURCE_DIR}/src/tracing/tracing-category-observer.cc
	${PROJECT_SOURCE_DIR}/src/trap-handler/handler-inside-posix.cc
	${PROJECT_SOURCE_DIR}/src/trap-handler/handler-inside.cc
	${PROJECT_SOURCE_DIR}/src/trap-handler/handler-outside-posix.cc
	${PROJECT_SOURCE_DIR}/src/trap-handler/handler-outside.cc
	${PROJECT_SOURCE_DIR}/src/trap-handler/handler-shared.cc
	${PROJECT_SOURCE_DIR}/src/utils/address-map.cc
	${PROJECT_SOURCE_DIR}/src/utils/allocation.cc
	${PROJECT_SOURCE_DIR}/src/utils/bit-vector.cc
	${PROJECT_SOURCE_DIR}/src/utils/detachable-vector.cc
	${PROJECT_SOURCE_DIR}/src/utils/hex-format.cc
	${PROJECT_SOURCE_DIR}/src/utils/identity-map.cc
	${PROJECT_SOURCE_DIR}/src/utils/memcopy.cc
	${PROJECT_SOURCE_DIR}/src/utils/ostreams.cc
	${PROJECT_SOURCE_DIR}/src/utils/sha-256.cc
	${PROJECT_SOURCE_DIR}/src/utils/utils.cc
	${PROJECT_SOURCE_DIR}/src/utils/v8dll-main.cc
	${PROJECT_SOURCE_DIR}/src/utils/version.cc
	${PROJECT_SOURCE_DIR}/src/wasm/baseline/liftoff-assembler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/baseline/liftoff-compiler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/c-api.cc
	${PROJECT_SOURCE_DIR}/src/wasm/canonical-types.cc
	${PROJECT_SOURCE_DIR}/src/wasm/code-space-access.cc
	${PROJECT_SOURCE_DIR}/src/wasm/constant-expression-interface.cc
	${PROJECT_SOURCE_DIR}/src/wasm/constant-expression.cc
	${PROJECT_SOURCE_DIR}/src/wasm/function-body-decoder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/function-compiler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/graph-builder-interface.cc
	${PROJECT_SOURCE_DIR}/src/wasm/jump-table-assembler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/local-decl-encoder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/memory-tracing.cc
	${PROJECT_SOURCE_DIR}/src/wasm/module-compiler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/module-decoder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/module-instantiate.cc
	${PROJECT_SOURCE_DIR}/src/wasm/names-provider.cc
	${PROJECT_SOURCE_DIR}/src/wasm/pgo.cc
	${PROJECT_SOURCE_DIR}/src/wasm/simd-shuffle.cc
	${PROJECT_SOURCE_DIR}/src/wasm/stacks.cc
	${PROJECT_SOURCE_DIR}/src/wasm/streaming-decoder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/sync-streaming-decoder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/value-type.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-code-manager.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-debug.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-disassembler.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-engine.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-external-refs.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-features.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-import-wrapper-cache.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-js.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-module-builder.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-module-sourcemap.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-module.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-objects.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-opcodes.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-result.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-serialization.cc
	${PROJECT_SOURCE_DIR}/src/wasm/wasm-subtyping.cc
	${PROJECT_SOURCE_DIR}/src/wasm/well-known-imports.cc
	${PROJECT_SOURCE_DIR}/src/zone/accounting-allocator.cc
	${PROJECT_SOURCE_DIR}/src/zone/type-stats.cc
	${PROJECT_SOURCE_DIR}/src/zone/zone-segment.cc
	${PROJECT_SOURCE_DIR}/src/zone/zone.cc
)
