if(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Windows")
    target_link_libraries(${name} winmm ws2_32 psapi dbghelp shlwapi urlmon
         userenv advapi32 kernel32 psapi iphlpapi userenv ws2_32)
else()
    if(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin")
        target_link_libraries(${name} dl iconv stdc++)
    elseif(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Linux")
        target_link_libraries(${name} dl rt)
    elseif(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "FreeBSD")
        find_library(execinfo execinfo "/usr/local/lib" "/usr/lib")
        target_link_libraries(${name} ${execinfo})
    endif()

	target_link_libraries(${name} pthread)
    if(NOT HAVE_GLIB_C_ATOMIC_H)
        target_link_libraries(${name} atomic)
    endif()
endif()
